= Exception

== Checked exceptions
checked and enforced at compile time
//Throwable and any subclass of Throwable that is not also a subclass of either RuntimeException or Error are regarded as checked exceptions.

[plantuml,scale=0.5,svg]
....
class Throwable {
  transient Object backtrace
  String detailMessage
  Throwable cause
  StackTraceElement[] stackTrace
}
Throwable *-right- StackTraceElement
class StackTraceElement {
  String declaringClass
  String methodName
  String fileName
  int    lineNumber
}
class Exception extends Throwable
class Error extends Throwable
class RuntimeException extends Exception

note "unchecked exceptions" as nce
Error .. nce
RuntimeException .. nce

note "indicate bugs!" as bug
RuntimeException .. bug
....

.StackTraceElement
. Each element represents a single stack frame.
. All stack frames except for the one at the top of the stack represent a method invocation.

:custom_exception: AuthorizationException
.common exception definition
[source,java,linenums,indent=0,subs=attributes+]
----
public class {custom_exception} extends RuntimeException {

    public {custom_exception}() {
        super();
    }

    public {custom_exception}(String message) {
        super(message);
    }

    public {custom_exception}(String message, Throwable cause) {
        super(message, cause);
    }

    public {custom_exception}(Throwable cause) {
        super(cause);
    }
}
----

[[InterruptedException]]
== InterruptedException
In Java, one thread cannot stop the other thread. A thread can only request the other thread to stop. The request is made in the form of an interruption.
[plantuml,scale=0.5,svg]
....
class InterruptedException extends Exception
....
[source,java,linenums,indent=0]
----
if (Thread.interrupted()) {  // Clears interrupted status!
    throw new InterruptedException(); // <1>
}
----
<1> InterruptedException is thrown and the current thread's interrupted status is cleared

=== use case
[source,java,linenums,indent=0]
----
public void run() {
    while (!Thread.currentThread().isInterrupted() && more work to do) { // <1>
        try {
            processTask(queue.take());
        } catch (InterruptedException e) {
            // Re-assert the threadâ€™s interrupted status
            Thread.currentThread().interrupt();
        }
    }
}
----
<1> cancellation points

[source,java,linenums,indent=0]
----
public void run() {
    try {
        while (!Thread.currentThread().isInterrupted() && more work to do) { // <1>
            ... do more work
        }
    } catch (InterruptedException e) {
        // thread is interrupted # <2>
    } finally {
        ... do clean work
    }
}
----
<1> cancellation points
<2> swallow the InterruptedException with the knowledge that the thread is about to terminate and that therefore there is no code higher up on the call stack that needs to know about the interruption.

[plantuml,scale=0.5,svg]
----
class InterruptedException extends Exception
class RuntimeException extends Exception
class IOException extends Exception
class SocketException extends IOException
class ClosedByInterruptException extends AsynchronousCloseException
class AsynchronousCloseException extends ClosedChannelException
class ClosedChannelException extends IOException
class ClosedSelectorException extends IllegalStateException
class IllegalStateException extends RuntimeException

note "Synchronous socket I/O in java.io" as io
note "Synchronous I/O in java.nio" as nio
note "Asynchronous I/O with Selector" as selector
note "Lock acquisition" as lock

SocketException -- io
ClosedChannelException -- nio
AsynchronousCloseException -- nio
ClosedSelectorException -- selector
InterruptedException -- lock
----

== throw Exception
filling in stack trace takes time, dependent on the stack depth

.disable the generation of the stack trace
----
-XX:-StackTraceInThrowable=false
----

classloader throw ClassNotFoundException

JVM reuse the system-generated exception, not contain a call stack
